# Generated by Django 3.2.3 on 2021-05-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Аннотация')),
            ],
            options={
                'verbose_name': 'Аннотацию',
                'verbose_name_plural': 'Аннотации',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательская компания')),
            ],
            options={
                'verbose_name': 'Издателя',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_series', models.IntegerField(verbose_name='Количество серий')),
            ],
            options={
                'verbose_name': 'Серию',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('unavailable', models.BooleanField(default=False, verbose_name='Нет в наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации Автора')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('annotation_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='manuals.annotation')),
                ('genre_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='manuals.genres')),
                ('publisher_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishers', to='manuals.publishers')),
                ('series_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='manuals.series')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
